name: Check DCO

on:
  pull_request:

permissions:
  contents: read

jobs:
  check-dco:
    name: Check DCO
    runs-on: ubuntu-22.04

    permissions:
      contents: read

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 #v4.2.2
        with:
          persist-credentials: false

      - uses: KineticCafe/actions-dco@a7f6488b8cadf38f423990df5fb9305dc33835ea #v1.3.2
        with:
          exempt-authors: |
            @kineticcommerce.com
            @kineticcafe.com
