name: Dependabot auto-merge

on:
  pull_request:

permissions:
  contents: read

jobs:
  dependabot-automerge:
    runs-on: ubuntu-22.04

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
        with:
          egress-policy: audit

      - uses: KineticCafe/actions/dependabot-automerge@3a2675f4bcbe3a8ae8dc6ad66da72b920792b37c #v2.0.0
        with:
          update-type: minor
          merge-type: rebase
